server:
  port: 8303

spring:
  application:
    name: service-activity
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_activity?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lzg13333733390*

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl