#网关服务端口
server:
  port: 8333

#服务名称
spring:
  application:
    name: service-gateway

  cloud:
    # nacos地址
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
      server-addr: nacos:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # 在网关中配置已有的微服务
      # service_vod
      routes:
        -
          id: service-vod
          # lb: load balance开启负载均衡
          uri: lb://service-vod
          # 配置路由断言，即路径映射, /admin/vod/xx
          predicates:
            - Path=/*/vod/**
        - id: service-order
          # lb: load balance开启负载均衡
          uri: lb://service-order
          # 配置路由断言，即路径映射, /admin/vod/xx
          predicates:
            - Path=/*/order/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**




